[package]
name = "gbemulator"
version = "0.1.0"
edition = "2021"
authors = ["Ron Popov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
readonly = "0.2.3"
clap = "4.0"
log = "0.4.17"
simplelog = "0.12.0"